// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsh4ssiVo-KFLOBOHFlm6Wa6rSL2yfeM8',
    appId: '1:486164113911:web:a85a6e8b78efb1590a66f2',
    messagingSenderId: '486164113911',
    projectId: 'task-pdf',
    authDomain: 'task-pdf.firebaseapp.com',
    storageBucket: 'task-pdf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwcL7Rd_mDvxvR78_bgPB0tHfv4nTzFCM',
    appId: '1:486164113911:android:7db0a3e85e69ba1f0a66f2',
    messagingSenderId: '486164113911',
    projectId: 'task-pdf',
    storageBucket: 'task-pdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjXfHBmAsga9m8O_F6hZNO445mh5-o408',
    appId: '1:486164113911:ios:6f440839338227f10a66f2',
    messagingSenderId: '486164113911',
    projectId: 'task-pdf',
    storageBucket: 'task-pdf.firebasestorage.app',
    iosBundleId: 'com.example.taskPdf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjXfHBmAsga9m8O_F6hZNO445mh5-o408',
    appId: '1:486164113911:ios:6f440839338227f10a66f2',
    messagingSenderId: '486164113911',
    projectId: 'task-pdf',
    storageBucket: 'task-pdf.firebasestorage.app',
    iosBundleId: 'com.example.taskPdf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsh4ssiVo-KFLOBOHFlm6Wa6rSL2yfeM8',
    appId: '1:486164113911:web:adf5feb808ad0d530a66f2',
    messagingSenderId: '486164113911',
    projectId: 'task-pdf',
    authDomain: 'task-pdf.firebaseapp.com',
    storageBucket: 'task-pdf.firebasestorage.app',
  );
}
